### PR TITLE
Bugfix/missing button types

### PR DESCRIPTION
**Pull request by adamturcsan**
Add type attributes to the buttons to avoid default submit

Issue #19

### CODE REVIEW

**Comment by dnwjn** [comment]
Hi @adamturcsan, you're absolutely right, I missed that one. Thanks for your PR!

**Comment by adamturcsan** [comment]
@dnwjn Thanks for the fast response and merge!

**Comment by adamturcsan** [comment]
@dnwjn I didn't bumped the version in the composer.json file and since its hardcoded there the git tags are not used as version numbers in Packagist and the new version doesn't appear there.
So either the version number in the composer.json file should be bumped or [it should be removed](https://getcomposer.org/doc/04-schema.md#version) to let git tags operate as version numbers.

**Comment by dnwjn** [comment]
> @dnwjn I didn't bumped the version in the composer.json file and since its hardcoded there the git tags are not used as version numbers in Packagist and the new version doesn't appear there.
> So either the version number in the composer.json file should be bumped or [it should be removed](https://getcomposer.org/doc/04-schema.md#version) to let git tags operate as version numbers.
> 

I realized this today as well, but I haven't had the time yet to change it. Will do that tomorrow first thing!

**Comment by dnwjn** [comment]
@adamturcsan Just removed the version from `composer.json` and released [v3.0.2](https://github.com/dnwjn/nova-button/releases/tag/3.0.2)!

**Pull request merged**
