### PR TITLE
FormField NovaButton no longer breaks form

### PR DESCRIPTION
**Pull request by sfinktah**
They really didn't work (didn't do anything when clicked, and broke form submission).  Fixed now.

### CODE REVIEW

**Comment by dnwjn** [comment]
@sfinktah Hi and thank you for your PR! Could you provide me a situation where it didn't work, so I can test it? Thanks!

**Comment by sfinktah** [comment]
> @sfinktah Hi and thank you for your PR! Could you provide me a situation where it didn't work, so I can test it? Thanks!

Not easily.  But looking at the changes I made, you can see that if you were creating a new resource, it would fail to display the button because a resourceId has yet to be allocated.

Having added my own (very nasty) fields to forms in Nova before, I also know that it will also fail because it has not returned a value (and Nova gets upset if it doesn't get a result for a field).

**Comment by dnwjn** [comment]
> > @sfinktah Hi and thank you for your PR! Could you provide me a situation where it didn't work, so I can test it? Thanks!
> 
> Not easily. But looking at the changes I made, you can see that if you were creating a new resource, it would fail to display the button because a resourceId has yet to be allocated.
> 
> Having added my own (very nasty) fields to forms in Nova before, I also know that it will also fail because it has not returned a value (and Nova gets upset if it doesn't get a result for a field).

Thank you for clearing it up. I did some testing and was able to reproduce the issue.

I went ahead and added more changes to your PR to make it more future-proof. I will be releasing this right away after merging it!

**Comment by sfinktah** [comment]
Thanks.. I see you changed the path in nova.mix.js from `../../vendor/laravel/nova/resources/js/mixins/packages.js', I should have caught that.  Of course it happens because `nova-components/Component/nova.mix.js` and `vendor/name/repo` are at two different levels from the root.

I have actually starting writing `/vendor/laravel/nova/` (absolute path), and will see how that works out.

I also noticed you removed the end of the path, so it's more like:  `../vendor/laravel/nova/resources/js`. I confess I'm not totally sure what that will do, but if it saves me having to manually add aliases from `@` to nova, I will add it to the stubs. :)

**Pull request merged**
