### PR TITLE
Nova.$emit events

### PR DESCRIPTION
**Pull request by sfinktah**
This is actually the only use-case I have for Nova Button, and it works great.

While I provided a short example in README.md, here's the full code I use (still a couple of functions I haven't pushed yet):

Note: I'm only pushing the code related to the line starting: `->emit(`
```php
                Button::make('Re-roll Tags')
                    ->stacked()
                    ->label("Clear OpenAI Cache")
                    ->event(RerollEvent::class, [$article_id, 'tags']) // added arguments to PHP events (untested and unused)
                    ->hideWhenCreating(false)
                    ->classes(explode(' ', 'shadow relative bg-primary-500 hover:bg-primary-400 text-white dark:text-gray-900 cursor-pointer rounded text-sm font-bold focus:outline-none focus:ring ring-primary-200 dark:ring-gray-600 inline-flex items-center justify-center h-9 px-3 shadow relative bg-primary-500 hover:bg-primary-400 text-white dark:text-gray-900'))
                    ->emit('reroll', ['article_id' => $article_id, 'which' => 'tags'])
                    ->reset() // allows button to be pressed again (re-enables 1 second after push)
                    ->onlyOnForms()
                    ->hideWhenUpdating()
                    ->help('When OpenAI does an epic fail, this clears the cache and tries again')
```

I fixed `help` and `label` to work as-per a standard Nova control, I think that was in my previous PR.

```js
            Nova.$on('reroll', (e) => {
                console.log('reroll', e);
                if (e.article_id) {
                    if (e.which === 'story') {
                        const element = document.querySelector("trix-editor");
                        const editor = element.editor
                        editor.loadDocument()
                    }
                    this.getOurStory(e.article_id, e.which === 'tags', e.which === 'story');
                }
            })
```

This is what it outputs like... ideally I would like both the buttons in a single row, but I haven't worked that one out yet.

image

### CODE REVIEW

**Comment by dnwjn** [comment]
@sfinktah This is great! I really appreciate your extensive descriptions and examples! 🚀 

I absolutely think this should be part of the package. Let me know when you have committed everything and I will process it!

**Comment by sfinktah** [comment]
@dnwjn probably best to keep them as distinct PRs, incase you want to roll any back later.   

The next two PRs, (the auto-reset on the button being available) and arguments the Illuminate\Event created in event might be tricker, as:

a) I couldn't come up with a very good name for the auto-reset method
b) I'm not 100% sure that Illuminate\Event works with arguments, as I don't use them

**Comment by sfinktah** [comment]
... and while I think of it, do you have any ideas on how to neatly allow multiple buttons in a single "row" (field) of a Nova form?

It seems that the correcrt answer would be a "ButtonGroup", similar to `Stack`... but it's a bit of an effort.

Easier (but hackier) would be something like:

```php
Button::make()->id('button1),
Button::make()->appendAfter('button1'),
```

I seem to recall in Nova 3 I used to use a plugin that allowed 1/2 width inputs that would slot together, but it's next to impossible to get those kind of invasive Nova 3 plugins working in Nova 4.

**Comment by sfinktah** [comment]
nvm, I ended up doing it the hard way (ButtonGroup), though I've only tested it with Form fields, it is unlikely to work on others.

image

```php
                ButtonGroup::make('Button Group', [
                    Button::make('Re-roll Story')
                        ->stacked()
                        ->label("Clear OpenAI Cache")
                        ->event(RerollEvent::class, [$article_id, 'story'])
                        ->hideWhenCreating(false)
                        ->classes('shadow relative bg-primary-500 hover:bg-primary-400 text-white dark:text-gray-900 cursor-pointer rounded text-sm font-bold focus:outline-none focus:ring ring-primary-200 dark:ring-gray-600 inline-flex items-center justify-center h-9 px-3 shadow relative bg-primary-500 hover:bg-primary-400 text-white dark:text-gray-900')
                        ->emit('reroll', ['article_id' => $article_id, 'which' => 'story'])
                        ->reset()
                    ,
                    // ...
                ])->stacked()->extraClasses('how many classes does a button-group have'),
```

**Comment by sfinktah** [comment]
@dnwjn can merge this single PR regarding the `emit` function, i just did a composer update and broke my code (no emit) :(

**Review by dnwjn — APPROVED** [review]

**Comment by dnwjn** [comment]
@sfinktah Apologies for taking so long, I've been super busy and haven't had the time to add changes where needed. I've done so now and will release a new version right away!

**Pull request merged**
